### ISSUE TITLE
Execute sql with entity parameter

### ISSUE THREAD

**Issue by chanh2505** [usausa/Smart-Net-Data-Accessor#2]
Hi usausa,

I wanna write a function with Execute attribute and parameter is an object. And it should be call my custom sql.
Maybe look like this: 
`[Execute]`
`int UpdateData(DataEntity entity)`

But I can't find any way to declare it. Please help me!

Thanks!

**Comment by usausa** [comment]
Like this.

* Entity & Accessor

```csharp
public class DataEntity
{
    public string Code { get; set; }

    public string Name { get; set; }
}
```

```csharp
[DataAccessor]
public interface IMasterAccessor
{
    [Execute]
    int UpdateData(DataEntity entity);
}
```

* IMasterAccessor.UpdateData.sql

```sql
UPDATE
    Data
SET
    Name = /*@ Name */'x'
WHERE
    Code = /*@ Code */'00'
```

Use property names for parameter names.

If you get a build error, check the messages in the output window.

**Comment by chanh2505** [comment]
Hi usausa,
This is the error output. Please help!

> Unhandled exception. Smart.Data.Accessor.Generator.AccessorGeneratorException: SQL load failed. type=[MyProject.DAL.IAccountAccessor], method=[Update], path=[E:\SourceCode\Backend\MyProject.DAL\Sql\IAccountAccessor.Update.sql]
   at Smart.Data.Accessor.Generator.FileSqlLoader.Load(MethodInfo mi) in .\Smart-Net-Data-Accessor\Smart.Data.Accessor.Generator.Core\FileSqlLoader.cs:line 58
   at Smart.Data.Accessor.Attributes.LoaderMethodAttribute.GetNodes(ISqlLoader loader, IGeneratorOption option, MethodInfo mi) in .\Smart-Net-Data-Accessor\Smart.Data.Accessor\Data\Accessor\Attributes\LoaderMethodAttribute.cs:line 21
   at Smart.Data.Accessor.Generator.DataAccessorGenerator.CreateSource(Type type) in .\Smart-Net-Data-Accessor\Smart.Data.Accessor.Generator.Core\DataAccessorGenerator.cs:line 50
   at Smart.Data.Accessor.Generator.DataAccessorGenerator.Generate(Type[] types) in .\Smart-Net-Data-Accessor\Smart.Data.Accessor.Generator.Core\DataAccessorGenerator.cs:line 31
   at Smart.Data.Accessor.Generator.Program.Main(String[] args) in .\Smart-Net-Data-Accessor\Smart.Data.Accessor.Generator.Tools\Program.cs:line 43

**Comment by usausa** [comment]
This exception message means that the sql file cannot be read.
Check if "E:\SourceCode\Backend\MyProject.DAL\Sql\IAccountAccessor.Update.sql" exists.

**Comment by chanh2505** [comment]
Hi usausa,
I found the root cause why it built failed.
I have wrong structure, Sql files are not in sub Sql folder follow this rule: [InterfaceAccessor Namespace] + Sql => path of sql folder.
You should mention for everybody.
Thanks
